name: flutter_xupdate
description: A Flutter plugin for XUpdate(Android Version Update Library).
version: 3.0.0

environment:
  sdk: ">=3.0.0 <5.0.0"
  flutter: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.xuexiang.flutter_xupdate
        pluginClass: FlutterXUpdatePlugin
